import sqlite3

con = sqlite3.connect("techpulse")
cursor = con.cursor()

cursor.executescript("""

-- =========================================================
-- DOCUMENTS
-- Stores submissions, comments, RSS articles, HN stories
-- =========================================================

CREATE TABLE IF NOT EXISTS documents (
    document_id TEXT PRIMARY KEY,
    document_type TEXT NOT NULL,
    source TEXT NOT NULL,
    source_item_id TEXT,

    parent_document_id TEXT,

    title TEXT,
    content TEXT NOT NULL,

    author TEXT,
    url TEXT,

    published_at TEXT NOT NULL,
    scraped_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (parent_document_id)
        REFERENCES documents(document_id)
);

-- =========================================================
-- ENTITIES
-- NVIDIA, Microsoft, OpenAI, AMD ...
-- =========================================================

CREATE TABLE IF NOT EXISTS entities (
    entity_id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_name TEXT NOT NULL UNIQUE,
    entity_type TEXT
);

-- =========================================================
-- DOCUMENT <-> ENTITY RELATIONSHIP
-- Many-to-many bridge
-- =========================================================

CREATE TABLE IF NOT EXISTS document_entities (
    document_id TEXT NOT NULL,
    entity_id INTEGER NOT NULL,
    mention_count INTEGER DEFAULT 1,

    PRIMARY KEY (document_id, entity_id),

    FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

    FOREIGN KEY (entity_id)
        REFERENCES entities(entity_id)
);

-- =========================================================
-- SENTIMENT RESULTS
-- Generated by NLP pipeline
-- =========================================================

CREATE TABLE IF NOT EXISTS sentiment (
    sentiment_id INTEGER PRIMARY KEY AUTOINCREMENT,

    document_id TEXT NOT NULL,
    entity_id INTEGER NOT NULL,

    sentiment_score REAL,
    sentiment_label TEXT,

    processed_at TEXT DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

    FOREIGN KEY (entity_id)
        REFERENCES entities(entity_id)
);

-- =========================================================
-- ENTITY -> STOCK SYMBOL
-- NVIDIA -> NVDA
-- Microsoft -> MSFT
-- =========================================================

CREATE TABLE IF NOT EXISTS ticker_mapping (
    entity_id INTEGER PRIMARY KEY,
    ticker TEXT NOT NULL UNIQUE,

    FOREIGN KEY (entity_id)
        REFERENCES entities(entity_id)
);

-- =========================================================
-- DAILY STOCK PRICES
-- =========================================================

CREATE TABLE IF NOT EXISTS stock_prices (
    ticker TEXT NOT NULL,
    price_date TEXT NOT NULL,

    open REAL,
    high REAL,
    low REAL,
    close REAL,

    volume INTEGER,

    PRIMARY KEY (ticker, price_date)
);

-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_documents_type
ON documents(document_type);

CREATE INDEX IF NOT EXISTS idx_documents_source
ON documents(source);

CREATE INDEX IF NOT EXISTS idx_documents_published
ON documents(published_at);

CREATE INDEX IF NOT EXISTS idx_documents_source_time
ON documents(source, published_at);

CREATE INDEX IF NOT EXISTS idx_documents_parent
ON documents(parent_document_id);

CREATE INDEX IF NOT EXISTS idx_document_entities_entity
ON document_entities(entity_id);

CREATE INDEX IF NOT EXISTS idx_sentiment_document
ON sentiment(document_id);

CREATE INDEX IF NOT EXISTS idx_sentiment_entity
ON sentiment(entity_id);

CREATE INDEX IF NOT EXISTS idx_sentiment_label
ON sentiment(sentiment_label);

""")

con.commit()
con.close()

print("TechPulse database created successfully")